# Generated by Django 3.1.8 on 2021-06-02 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superheroes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='superhero',
            name='catchphrase',
            field=models.CharField(default='Hello', max_length=50),
            preserve_default=False,
        ),
    ]
